apiVersion: v1
kind: Pod
metadata:
  name: db-tasty
  labels:
    app: db-tasty
spec:
  containers:
    - name: tasty-postgres
      image: postgres
      ports:
        - containerPort: 5432
      envFrom:
        - configMapRef:
           name: db-configmap