apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: replicaset-sistema-tasty
spec:
  template:
    metadata:
      name: sistema-tasty
      labels:
        app: sistema-tasty
    spec:
        containers:
        - name: sistema-tasty
          image: llaugustoll/tasty_delivery:v6
          ports:
            - containerPort: 8000
          envFrom:
            - configMapRef:
                name: configmap-tasty-sistema  
  replicas: 2
  selector:
    matchLabels:
      app: sistema-tasty
